version: "3"

services:
  rathole:
    image: rapiz1/rathole:latest      
    ##network_mode: host    
    restart: unless-stopped
    entrypoint: "./rathole /app/config.toml"
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - ${network_name}
    deploy:
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
        # Make the traefik service run only on the node with this label
        # as the node with it has the volume for the certificates
        #- node.labels.${network_name}.${network_name}-certificates == true
          - node.role == manager
    configs:
      - source: rathole_config_toml
        target: /app/config.toml
    secrets:
      - RATHOLE_DEFAULT_TOKEN
      - RATHOLE_CONNECTION_PORT
      - RATHOLE_ADDRESS

networks:
  ${network_name}:
    external: true

configs:
  rathole_config_toml:
    external: true

secrets:
  RATHOLE_DEFAULT_TOKEN:
    external: true
  RATHOLE_CONNECTION_PORT:
    external: true
  RATHOLE_ADDRESS:
    external: true