version: '3.9'
services:
  authelia:
    image: 'docker.io/authelia/authelia:latest'
    networks:
      - overlay_public
    environment:
      X_AUTHELIA_CONFIG_FILTERS: 'template'
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/AUTHELIA_JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/AUTHELIA_SESSION_SECRET'
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/run/secrets/AUTHELIA_STORAGE_POSTGRES_PASSWORD'
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: '/run/secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY'
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: '/run/secrets/AUTHELIA_OIDC_HMAC'
      TZ: 'Europe/Berlin'
    volumes:
      - 'authelia_log:/runTime/logs/'
    secrets: 
      - 'DOMAIN_NAME'
      - 'ADMIN_MAIL'
      - 'AUTHELIA_JWT_SECRET'
      - 'AUTHELIA_SESSION_SECRET'
      - 'AUTHELIA_STORAGE_POSTGRES_PASSWORD'
      - 'AUTHELIA_NOTIFIER_SMTP_PASSWORD'
      - 'AUTHELIA_STORAGE_ENCRYPTION_KEY'
      - 'AUTHELIA_OIDC_HMAC'
      - 'AUTHELIA_OIDC_JWKS_KEY'
      - 'AUTHELIA_OIDC_IMMICH_HASH'
      - 'AUTHELIA_OIDC_HOMARR_HASH'
      - 'AUTHELIA_OIDC_JELLYFIN_HASH'
      - 'AUTHELIA_OIDC_PAPERLESS_HASH'
      - 'AUTHELIA_OIDC_PORTAINER_HASH'
      - 'AUTHELIA_OIDC_SEAFILE_HASH'
      - 'AUTHELIA_OIDC_CLOUDFLARE_HASH'
    configs:
      - source: authelia_config
        target: /config/configuration.yml
      - source: authelia_users
        target: /runTime/users_database.yml
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.authelia.entrypoints=https-external,https'
        - 'traefik.http.routers.authelia.rule=Host(`auth.${domain}`)'
        - 'traefik.http.routers.authelia.tls=true'
        - 'traefik.http.services.authelia.loadbalancer.server.port=9091'
        - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth?authelia_url=https://auth.${domain}'
        - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=false'
        - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  

networks:
  # Use the previously created public network "overlay_public", shared with other
  # services that need to be publicly available via this Traefik
  overlay_public:
    external: true

volumes:
  authelia_log:

secrets:
  DOMAIN_NAME:
    external: true
  ADMIN_MAIL:
    external: true
  AUTHELIA_JWT_SECRET:
    external: true
  AUTHELIA_SESSION_SECRET:
    external: true
  AUTHELIA_STORAGE_POSTGRES_PASSWORD:
    external: true
  AUTHELIA_STORAGE_ENCRYPTION_KEY:
    external: true
  AUTHELIA_NOTIFIER_SMTP_PASSWORD:
    external: true
  AUTHELIA_OIDC_HMAC:
    external: true
  AUTHELIA_OIDC_JWKS_KEY:
    external: true
  AUTHELIA_OIDC_IMMICH_HASH:
    external: true
  AUTHELIA_OIDC_HOMARR_HASH:
    external: true
  AUTHELIA_OIDC_JELLYFIN_HASH:
    external: true
  AUTHELIA_OIDC_PAPERLESS_HASH:
    external: true
  AUTHELIA_OIDC_PORTAINER_HASH:
    external: true
  AUTHELIA_OIDC_SEAFILE_HASH:
    external: true

configs:
  authelia_config:
    external: true
  authelia_users:
    external: true