version: '3.3'

services:
  authelia:
    image: 'docker.io/authelia/authelia:latest'
    networks:
      - overlay_public
    environment:
      X_AUTHELIA_CONFIG_FILTERS: 'template'
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: '/run/secrets/AUTHELIA_JWT_SECRET'
      AUTHELIA_SESSION_SECRET_FILE: '/run/secrets/AUTHELIA_SESSION_SECRET'
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: '/run/secrets/AUTHELIA_STORAGE_POSTGRES_PASSWORD'
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: '/run/secrets/AUTHELIA_NOTIFIER_SMTP_PASSWORD'
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: '/run/secrets/AUTHELIA_STORAGE_ENCRYPTION_KEY'
      AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE: '/run/secrets/AUTHELIA_OIDC_HMAC'
      TZ: 'Europe/Berlin'
    volumes:
      - '${authelia_config_folder}/authelia:/config'
      - '/var/data/authelia:/runTime'
    secrets: 
      - 'DOMAIN_NAME'
      - 'AUTHELIA_JWT_SECRET'
      - 'AUTHELIA_SESSION_SECRET'
      - 'AUTHELIA_STORAGE_POSTGRES_PASSWORD'
      - 'AUTHELIA_NOTIFIER_SMTP_PASSWORD'
      - 'AUTHELIA_STORAGE_ENCRYPTION_KEY'
      - 'AUTHELIA_OIDC_HMAC'
      - 'AUTHELIA_OIDC_JWKS_KEY'
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.authelia.entrypoints=https-external,https'
        - 'traefik.http.routers.authelia.rule=Host(`auth.${domain}`)'
        - 'traefik.http.routers.authelia.tls=true'
        - 'traefik.http.services.authelia.loadbalancer.server.port=9091'
        - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth?authelia_url=https://auth.${domain}'
        - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=false'
        - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'  

networks:
  # Use the previously created public network "overlay_public", shared with other
  # services that need to be publicly available via this Traefik
  overlay_public:
    external: true

secrets:
  AUTHELIA_JWT_SECRET:
    external: true
  AUTHELIA_SESSION_SECRET:
    external: true
  AUTHELIA_STORAGE_POSTGRES_PASSWORD:
    external: true
  AUTHELIA_STORAGE_ENCRYPTION_KEY:
    external: true
  AUTHELIA_NOTIFIER_SMTP_PASSWORD:
    external: true
  AUTHELIA_STORAGE_ENCRYPTION_KEY:
    external: true
  AUTHELIA_OIDC_HMAC:
    external: true
  AUTHELIA_OIDC_JWKS_KEY:
    external: true
  DOMAIN_NAME:
    external: true
