theme: 'auto'
default_2fa_method: 'totp'
server:
  address: 'tcp://:9091'
log:
  level: 'info'
  file_path: '/runTime/logs/authelia.log'
totp:
  disable: false
  issuer: '{{ secret "/run/secrets/DOMAIN_NAME" }}'
webauthn:
  disable: false
  display_name: 'Authelia'
  attestation_conveyance_preference: 'indirect'
  user_verification: 'preferred'
  timeout: '60s'
authentication_backend:
  password_reset:
    disable: true
  file:
    path: '/runTime/users_database.yml'
    watch: true
password_policy:
  standard:
    enabled: false
  zxcvbn:
    enabled: true
    min_score: 3
access_control:
  default_policy: 'deny'
  rules:
    - domain: '*.{{ secret "/run/secrets/DOMAIN_NAME" }}'
      policy: 'two_factor'
session:
  cookies:
    - name: 'authelia_session'
      domain: '{{ secret "/run/secrets/DOMAIN_NAME" }}'
      authelia_url: 'https://auth.{{ secret "/run/secrets/DOMAIN_NAME" }}'
      expiration: '1 hour'
      inactivity: '5 minutes'
  redis:
    host: 'redis'
    port: 6379
    database_index: 0
regulation:
  max_retries: 3
  find_time: '2 minutes'
  ban_time: '5 minutes'
storage:
  postgres:
    address: 'tcp://db:5432'
    database: 'authelia'
    schema: 'public'
    username: 'authelia'
    password: #set via secret
notifier:
  disable_startup_check: false
  smtp:
    username: '{{ secret "/run/secrets/ADMIN_MAIL" }}'
    #password: AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
    sender: 'admin@{{ secret "/run/secrets/DOMAIN_NAME" }}'
    address: 'submission://smtp.gmail.com:587'
identity_providers:
  oidc:
    jwks:
      - key_id: 'example'
        key: {{ secret "/run/secrets/AUTHELIA_OIDC_JWKS_KEY" | mindent 10 "|" | msquote }}
    authorization_policies:
      standard:
        default_policy: 'two_factor'
        rules:
         - policy: 'deny'
           subject: 'group:services'
    clients:
      - client_id: 'immich'
        client_name: 'immich'
        client_secret: {{ secret "/run/secrets/AUTHELIA_OIDC_IMMICH_HASH" | mindent 10 "|" | msquote }} #hashed
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://photos.{{ secret "/run/secrets/DOMAIN_NAME" }}/auth/login'
          - 'https://photos.{{ secret "/run/secrets/DOMAIN_NAME" }}/user-settings'
          - 'app.immich:/'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
      - client_id: 'homarr'
        client_name: 'Homarr'
        client_secret: {{ secret "/run/secrets/AUTHELIA_OIDC_HOMARR_HASH" | mindent 10 "|" | msquote }} #hashed
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'http://home.{{ secret "/run/secrets/DOMAIN_NAME" }}/api/auth/callback/oidc'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
        #consent_mode: implicit # self hosted
      - client_id: 'jellyfin'
        client_name: 'Jellyfin'
        client_secret: {{ secret "/run/secrets/AUTHELIA_OIDC_JELLYFIN_HASH" | mindent 10 "|" | msquote }} #hashed
        public: false
        authorization_policy: 'two_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://media.{{ secret "/run/secrets/DOMAIN_NAME" }}/sso/OID/redirect/authelia'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_post'
      - client_id: 'paperless'
        client_name: 'Paperless'
        client_secret: {{ secret "/run/secrets/AUTHELIA_OIDC_PAPERLESS_HASH" | mindent 10 "|" | msquote }} #hashed
        public: false
        authorization_policy: 'two_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        redirect_uris:
          - 'https://docs.{{ secret "/run/secrets/DOMAIN_NAME" }}/accounts/oidc/authelia/login/callback/'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
          - 'groups'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'
      - client_id: 'portainer'
        client_name: 'Portainer'
        client_secret: {{ secret "/run/secrets/AUTHELIA_OIDC_PORTAINER_HASH" | mindent 10 "|" | msquote }} #hashed
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://portainer.{{ secret "/run/secrets/DOMAIN_NAME" }}'
        scopes:
          - 'openid'
          - 'profile'
          - 'groups'
          - 'email'
        userinfo_signed_response_alg: 'none'
      - client_id: 'seafile'
        client_name: 'Seafile'
        client_secret: {{ secret "/run/secrets/AUTHELIA_OIDC_SEAFILE_HASH" | mindent 10 "|" | msquote }} #hashed
        public: false
        authorization_policy: 'two_factor'
        redirect_uris:
          - 'https://files.{{ secret "/run/secrets/DOMAIN_NAME" }}/oauth/callback/'
        scopes:
          - 'openid'
          - 'profile'
          - 'email'
        userinfo_signed_response_alg: 'none'
        token_endpoint_auth_method: 'client_secret_basic'