version: "3.8"
services:
  pgadmin:
    image: dpage/pgadmin4
    #ports:
    #  - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: '${admin_mail}'
      PGADMIN_DEFAULT_PASSWORD_FILE: '/run/secrets/PGADMIN_DEFAULT_PASSWORD'
    secrets:
      - PGADMIN_DEFAULT_PASSWORD
    volumes:
      - 'data:/var/lib/pgadmin'
    networks:
      - ${network_name}
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.pgadmin.entrypoints=https'
        - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.${domain}`)'
        - 'traefik.http.routers.pgadmin.tls=true'
        - 'traefik.http.services.pgadmin.loadbalancer.server.port=80'
        - "traefik.http.routers.pgadmin.middlewares=authelia@swarm"

secrets:
  PGADMIN_DEFAULT_PASSWORD:
    external: true

networks:
  ${network_name}:
    external: true

volumes:
  data:
