version: '3.9'

# What is this?
#
# This stack exists solely to deploy the traefik_public overlay network, so that
# other stacks (including traefik-app) can attach to it

services:
  scratch:
    image: scratch
    deploy: 
      replicas: 0
    networks:
      - defaultNetwork

networks:
  defaultNetwork:
    name: ${network_name:?err}
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: ${subnet} #172.16.200.0/24

