version: "3"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
      #- 3000:3000/tcp
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    networks:
      - ${network_name}
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.dns.rule=Host(`dns.${domain}`)'
        - 'traefik.http.routers.dns.entrypoints=https'
        - 'traefik.http.routers.dns.tls=true'
        - 'traefik.http.services.dns.loadbalancer.server.port=3000'
        - 'traefik.http.routers.dns.middlewares=authelia@swarm'
    restart: unless-stopped

networks:
  ${network_name}:
    external: true

volumes:
  adguard_work:
  adguard_conf: