version: '3.1'

services:
  db:
    image: postgres
    restart: always
    networks:
      - ${db_network_name}
    # set shared memory limit when deploy via swarm stack
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: run/secrets/POSTGRES_ROOT_PASSWORD
    secrets:
      - POSTGRES_ROOT_PASSWORD
    deploy:
      labels:
        - "traefik.enable=false"

networks:
  # Use the previously created public network "${db_network_name}", shared with other
  # services that need to be publicly available via this Traefik
  ${db_network_name}:
    external: true

volumes:
  data:

secrets:
  POSTGRES_ROOT_PASSWORD:
    external: true