version: '3.9'

services:
  db:
    image: postgres
    restart: always
    networks:
      - overlay
    # set shared memory limit when deploy via swarm stack
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: run/secrets/POSTGRES_ROOT_PASSWORD
    secrets:
      - POSTGRES_ROOT_PASSWORD
    deploy:
      labels:
        - "traefik.enable=false"

networks:
  # Use the previously created public network "overlay", shared with other
  # services that need to be publicly available via this Traefik
  overlay:
    driver: overlay
    internal: true
    attachable: true
    ipam:
      config:
        - subnet: ${subnet} #172.16.200.0/24

volumes:
  data:

secrets:
  POSTGRES_ROOT_PASSWORD:
    external: true