version: "3.9"

services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    volumes:
      - ${home_folder}/media/entertainment/lib:/config
      - ${home_folder}/media/entertainment/tvshows:/data/tvshows
      - ${home_folder}/media/entertainment/movies:/data/movies
    environment:
      - 'PUID=1000'
      - 'GUID=1000'
      - 'TZ=Europe/Berlin'
      - 'DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel'
      - 'JELLYFIN_PublishedServerUrl=${AutoDiscover_HomeServer_Response}'
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.rule=Host(`media.dmaier.top`)"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        - 'traefik.http.routers.jellyfin.tls=true'
        - 'traefik.http.routers.jellyfin.tls.certresolver=cloudflare'
        #- 'traefik.http.routers.jellyfin.tls.domains[0].main=${domain}'
        #- 'traefik.http.routers.jellyfin.tls.domains[0].sans=*.${domain}'
        - 'traefik.http.routers.jellyfin.entrypoints=https,https-external'
    networks:
        - defaultNetwork
    ports:
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional

networks:
  defaultNetwork:
    name: ${network_name}
    external: true