version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin
    env_file: /var/data/config/jellyfin/jellyfin.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - cache:/cache
      - ${home_folder}/media/entertainment:/data
    environment:
      - PUID: 1000
      - GUID: 1000
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyfin.rule=Host(`movies.dmaier.top`)"
        - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
        - 'traefik.http.routers.jellyfin.tls=true'
        - 'traefik.http.routers.jellyfin.tls.certresolver=cloudflare'
        - 'traefik.http.routers.jellyfin.tls.domains[0].main=${domain}'
        - 'traefik.http.routers.jellyfin.tls.domains[0].sans=*.${domain}'
        - 'traefik.http.routers.jellyfin.entrypoints=https,https-external'
    networks:
        - defaultNetwork
    #ports:
    #  - 8096:8096

networks:
  defaultNetwork:
    name: ${network_name}
    external: true