version: '3.2'

services:
  portainer:
    image: portainer/portainer-ce:sts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/data/portainer:/data
    networks:
      - internal
      - ${network_name}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        # traefik
        - traefik.enable=true
        - traefik.docker.network=${network_name}
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
        # traefikv2
        - "traefik.http.routers.portainer.rule=Host(`portainer.${domain}`)"
        - 'traefik.http.routers.portainer.tls=true'
        - 'traefik.http.routers.portainer.tls.certresolver=cloudflare'
        - 'traefik.http.routers.portainer.tls.domains[0].main=${domain}'
        - 'traefik.http.routers.portainer.tls.domains[0].sans=*.${domain}'
        - 'traefik.http.routers.portainer.entrypoints=https'

  agent:
    image: portainer/agent:sts
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - internal
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

networks:
  ${network_name}:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.13.0/24