version: '3.3'

services:
  redis:
    image: redis:alpine
    volumes:
      - /var/data/redis:/data
    networks:
      - overlay_public
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    deploy:
      labels:
         - "traefik.enable=false"

networks:
  # Use the previously created public network "overlay_public", shared with other
  # services that need to be publicly available via this Traefik
  overlay_public:
    external: true