version: '3.3'

services:
  redis:
    image: redis:alpine
    volumes:
      - data:/data
    networks:
      - ${redis_network_name}
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    deploy:
      labels:
         - "traefik.enable=false"

networks:
  # Use the previously created public network "${redis_network_name}", shared with other
  # services that need to be publicly available via this Traefik
  ${redis_network_name}:
    external: true

volume:
  data: