version: '3.9'

services:
  redis:
    image: redis:alpine
    volumes:
      - data:/data
    networks:
      - redis_network
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    deploy:
      labels:
         - "traefik.enable=false"

networks:
  redis_network:
    name: ${redis_network_name}

volume:
  data: