version: "3.9"

services:
  redis:
    image: redis:alpine
    volumes:
      - data:/data
    networks:
      - overlay
    expose:
      - 6379
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    deploy:
      labels:
        - "traefik.enable=false"

networks:
  overlay:
    driver: overlay
    internal: true
    attachable: true
    ipam:
      config:
        - subnet: ${subnet} #172.16.200.0/24

volumes:
  data:
    driver: linstor
    driver_opts:
      size: "${storage_size}"
      filesystem: "ext4"
      storagepool: linstor_docker
